"""empty message

Revision ID: 0bb4f779bf64
Revises: 767bc158eb30
Create Date: 2019-02-09 08:50:36.370525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb4f779bf64'
down_revision = '767bc158eb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cMake', sa.String(length=128), nullable=True),
    sa.Column('cModel', sa.String(length=128), nullable=True),
    sa.Column('cYear', sa.Integer(), nullable=True),
    sa.Column('fCost', sa.Integer(), nullable=True),
    sa.Column('fType', sa.String(length=32), nullable=True),
    sa.Column('hMpg', sa.Integer(), nullable=True),
    sa.Column('cMpg', sa.Integer(), nullable=True),
    sa.Column('comboMpg', sa.Integer(), nullable=True),
    sa.Column('transType', sa.String(length=32), nullable=True),
    sa.Column('coTwo', sa.Float(), nullable=True),
    sa.Column('saveSpend', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_cMake'), 'car', ['cMake'], unique=False)
    op.create_index(op.f('ix_car_cModel'), 'car', ['cModel'], unique=True)
    op.create_index(op.f('ix_car_cMpg'), 'car', ['cMpg'], unique=False)
    op.create_index(op.f('ix_car_cYear'), 'car', ['cYear'], unique=False)
    op.create_index(op.f('ix_car_coTwo'), 'car', ['coTwo'], unique=False)
    op.create_index(op.f('ix_car_comboMpg'), 'car', ['comboMpg'], unique=False)
    op.create_index(op.f('ix_car_fCost'), 'car', ['fCost'], unique=False)
    op.create_index(op.f('ix_car_fType'), 'car', ['fType'], unique=False)
    op.create_index(op.f('ix_car_hMpg'), 'car', ['hMpg'], unique=False)
    op.create_index(op.f('ix_car_saveSpend'), 'car', ['saveSpend'], unique=False)
    op.create_index(op.f('ix_car_transType'), 'car', ['transType'], unique=False)
    op.drop_index('ix_user_make', table_name='user')
    op.drop_index('ix_user_model', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('make', sa.VARCHAR(length=120), nullable=True),
    sa.Column('model', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_model', 'user', ['model'], unique=1)
    op.create_index('ix_user_make', 'user', ['make'], unique=False)
    op.drop_index(op.f('ix_car_transType'), table_name='car')
    op.drop_index(op.f('ix_car_saveSpend'), table_name='car')
    op.drop_index(op.f('ix_car_hMpg'), table_name='car')
    op.drop_index(op.f('ix_car_fType'), table_name='car')
    op.drop_index(op.f('ix_car_fCost'), table_name='car')
    op.drop_index(op.f('ix_car_comboMpg'), table_name='car')
    op.drop_index(op.f('ix_car_coTwo'), table_name='car')
    op.drop_index(op.f('ix_car_cYear'), table_name='car')
    op.drop_index(op.f('ix_car_cMpg'), table_name='car')
    op.drop_index(op.f('ix_car_cModel'), table_name='car')
    op.drop_index(op.f('ix_car_cMake'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
