"""car table

Revision ID: 767bc158eb30
Revises: 
Create Date: 2019-02-08 21:46:53.058363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767bc158eb30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_make'), 'user', ['make'], unique=False)
    op.create_index(op.f('ix_user_model'), 'user', ['model'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_model'), table_name='user')
    op.drop_index(op.f('ix_user_make'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
